### PR TITLE
Rate limit users for incorrect flag submission

### LINKED ISSUE #62: Ratelimit the user from flag submission

### PR DESCRIPTION
**Pull request by samueltangz**
* Implement a 30-second delay for each incorrect flag submission to
  the particular challenge to avoid brute forcing

Closes #62

### CODE REVIEW

File: back-end/src/api/challenges.js [hunk 1]
```diff
@@ -36,12 +36,19 @@ router.post('/:id(\\d+)/flag', authenticate, [
...
+  const wrongFlagSubmission = await db.redis.get(`flagSubmission/${user.id}/${id}`)
+  if (wrongFlagSubmission) return res.status(429).json({ error: 'You cannot submit flags too frequently.' })
+
+  const { flag } = req.body
   if (challenge.authorId === user.id) return res.status(403).json({ error: 'You do not have enough permissions' })
   const challengeLog = await db.ChallengeLogs.findOne({ userId: user.id, challengeId: id })
   if (challengeLog) return res.status(400).json({ error: 'Already solved challenge' })
-  if (flag !== challenge.flag) return res.status(400).json({ error: 'Wrong flag' })
+  if (flag !== challenge.flag) {
+    await db.redis.set(`flagSubmission/${user.id}/${id}`, '1', 'EX', 30)
```
Comment (harrier-lcc) [inline back-end/src/api/challenges.js]: should set time as configurable (?
